export const metadata = {
  title: "Api Tester",
  description: "Generated by Next.js",
};
import React from "react";
import "./globals.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#09051a] text-[#e8e8e8]">{children}</body>
    </html>
  );
}
